site_name: pushfill __VERSION__
site_description: Fill a disk with pseudo-random data as fast as possible
site_url: https://gitlab.com/waterjuice/pushfill
use_directory_urls: false

repo_url: https://gitlab.com/waterjuice/pushfill
repo_name: waterjuice/pushfill

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.sections

copyright: "&copy; 2026 WaterJuice"

nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - How It Works: how-it-works.md
  - History: history.md
  - Licence: licence.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
